/** Tradeneu Privacy Policy — product legal copy for in-app display. */

export const TRADENEU_PRIVACY_UPDATED = 'July 26, 2026'

export const TRADENEU_PRIVACY_TITLE = 'Privacy Policy for Tradeneu'

export function getTradeneuPrivacyHtml(): string {
  return `
<p class="sx-legal__lead"><strong>Privacy Policy</strong><br/>Last updated: ${TRADENEU_PRIVACY_UPDATED}</p>

<p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>

<p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

<h3>Interpretation and Definitions</h3>
<h4>Interpretation</h4>
<p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

<h4>Definitions</h4>
<p>For the purposes of this Privacy Policy:</p>
<ul>
  <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
  <li><strong>Business</strong>, for the purpose of the CCPA (California Consumer Privacy Act), refers to the Company as the legal entity that collects Consumers' personal information and determines the purposes and means of the processing of Consumers' personal information, or on behalf of which such information is collected and that alone, or jointly with others, determines the purposes and means of the processing of consumers' personal information, that does business in the State of California.</li>
  <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Tradeneu and the operator of the Website and Services. Contact details are published on the Website and at the end of this Policy.</li>
  <li><strong>Consumer</strong>, for the purpose of the CCPA (California Consumer Privacy Act), means a natural person who is a California resident. A resident, as defined in the law, includes (1) every individual who is in the USA for other than a temporary or transitory purpose, and (2) every individual who is domiciled in the USA who is outside the USA for a temporary or transitory purpose.</li>
  <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
  <li><strong>Country</strong> refers to the jurisdiction where Tradeneu principally operates, as designated on the Website.</li>
  <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
  <li><strong>Do Not Track (DNT)</strong> is a concept that has been promoted by US regulatory authorities, in particular the U.S. Federal Trade Commission (FTC), for the Internet industry to develop and implement a mechanism for allowing internet users to control the tracking of their online activities across websites.</li>
  <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual. For the purposes of the CCPA, Personal Data means any information that identifies, relates to, describes or is capable of being associated with, or could reasonably be linked, directly or indirectly, with You.</li>
  <li><strong>Sale</strong>, for the purpose of the CCPA (California Consumer Privacy Act), means selling, renting, releasing, disclosing, disseminating, making available, transferring, or otherwise communicating orally, in writing, or by electronic or other means, a Consumer's personal information to another business or a third party for monetary or other valuable consideration.</li>
  <li><strong>Service</strong> refers to the Website and Tradeneu applications associated with it, including trading simulation, charting, replay, and related tools.</li>
  <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
  <li><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
  <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
  <li><strong>Website</strong> refers to Tradeneu, accessible from the Tradeneu domain published by Us.</li>
  <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
</ul>

<h3>Collecting and Using Your Personal Data</h3>
<h4>Types of Data Collected</h4>
<h4>Personal Data</h4>
<p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
<ul>
  <li>Email address</li>
  <li>First name and last name</li>
  <li>Mobile number (when provided during registration)</li>
  <li>Usage Data</li>
</ul>

<h4>Usage Data</h4>
<p>Usage Data is collected automatically when using the Service.</p>
<p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
<p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
<p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>

<h4>Information from Third-Party Social Media Services</h4>
<p>The Company may allow You to create an account and log in to use the Service through the following Third-party Social Media Services:</p>
<ul>
  <li>Google</li>
</ul>
<p>Additional providers may be added over time and will be listed here when available.</p>
<p>If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.</p>
<p>You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.</p>

<h4>Tracking Technologies and Cookies</h4>
<p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used may include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
<ul>
  <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
  <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
</ul>
<p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
<p>We use both Session and Persistent Cookies for the purposes set out below:</p>
<ul>
  <li><strong>Necessary / Essential Cookies</strong> — Type: Session Cookies. Administered by: Us. Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided.</li>
  <li><strong>Cookies Policy / Notice Acceptance Cookies</strong> — Type: Persistent Cookies. Administered by: Us. Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</li>
  <li><strong>Functionality Cookies</strong> — Type: Persistent Cookies. Administered by: Us. Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference.</li>
  <li><strong>Tracking and Performance Cookies</strong> — Type: Persistent Cookies. Administered by: Third-Parties (when enabled). Purpose: These Cookies are used to track information about traffic to the Website and how users use the Website. The information gathered via these Cookies may directly or indirectly identify you as an individual visitor.</li>
</ul>

<h3>Use of Your Personal Data</h3>
<p>The Company may use Personal Data for the following purposes:</p>
<ul>
  <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
  <li>To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
  <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
  <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
  <li>To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
  <li>To manage Your requests: To attend and manage Your requests to Us.</li>
  <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
  <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
</ul>
<p>We may share Your personal information in the following situations:</p>
<ul>
  <li><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, for payment processing, to contact You.</li>
  <li><strong>For business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
  <li><strong>With Affiliates:</strong> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy.</li>
  <li><strong>With business partners:</strong> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
  <li><strong>With other users:</strong> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
  <li><strong>With Your consent:</strong> We may disclose Your personal information for any other purpose with Your consent.</li>
</ul>

<h3>Retention of Your Personal Data</h3>
<p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
<p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>

<h3>Transfer of Your Personal Data</h3>
<p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
<p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
<p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>

<h3>Delete Your Personal Data</h3>
<p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
<p>Our Service may give You the ability to delete certain information about You from within the Service.</p>
<p>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</p>
<p>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>

<h3>Disclosure of Your Personal Data</h3>
<h4>Business Transactions</h4>
<p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
<h4>Law enforcement</h4>
<p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
<h4>Other legal requirements</h4>
<p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
<ul>
  <li>Comply with a legal obligation</li>
  <li>Protect and defend the rights or property of the Company</li>
  <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
  <li>Protect the personal safety of Users of the Service or the public</li>
  <li>Protect against legal liability</li>
</ul>

<h3>Security of Your Personal Data</h3>
<p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

<h3>Detailed Information on the Processing of Your Personal Data</h3>
<p>The Service Providers We use may have access to Your Personal Data. These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies.</p>

<h4>Analytics</h4>
<p>We may use third-party Service providers to monitor and analyze the use of our Service.</p>
<p><strong>Google Analytics</strong> — Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. For more information on the privacy practices of Google, please visit: <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy</a>.</p>
<p><strong>Firebase</strong> — Firebase is an analytics service provided by Google Inc. You may opt-out of certain Firebase features through your mobile device settings or by following the instructions provided by Google in their Privacy Policy: <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">https://policies.google.com/privacy</a>.</p>

<h4>Payments</h4>
<p>We may provide paid products and/or services within the Service. In that case, we may use third-party services for payment processing (e.g. payment processors).</p>
<p>We will not store or collect Your payment card details. That information is provided directly to Our third-party payment processors whose use of Your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council.</p>
<p><strong>Stripe</strong> — Their Privacy Policy can be viewed at <a href="https://stripe.com/privacy" target="_blank" rel="noopener noreferrer">https://stripe.com/privacy</a>.</p>

<h4>Usage, Performance and Miscellaneous</h4>
<p>We may use third-party Service Providers to provide better improvement of our Service.</p>
<p><strong>Invisible reCAPTCHA</strong> — We may use an invisible captcha service named reCAPTCHA operated by Google. The reCAPTCHA service may collect information from You and from Your Device for security purposes. The information gathered by reCAPTCHA is held in accordance with the Privacy Policy of Google: <a href="https://www.google.com/intl/en/policies/privacy/" target="_blank" rel="noopener noreferrer">https://www.google.com/intl/en/policies/privacy/</a>.</p>

<h3>CCPA Privacy</h3>
<p>This privacy notice section for California residents supplements the information contained in Our Privacy Policy and it applies solely to all visitors, users, and others who reside in the State of California.</p>

<h4>Categories of Personal Information Collected</h4>
<p>We collect information that identifies, relates to, describes, references, is capable of being associated with, or could reasonably be linked, directly or indirectly, with a particular Consumer or Device. The following is a list of categories of personal information which we may collect or may have been collected from California residents within the last twelve (12) months.</p>
<p>Please note that the categories and examples provided in the list below are those defined in the CCPA. This does not mean that all examples of that category of personal information were in fact collected by Us, but reflects our good faith belief to the best of our knowledge that some of that information from the applicable category may be and may have been collected.</p>
<ul>
  <li><strong>Category A: Identifiers.</strong> Examples: A real name, alias, postal address, unique personal identifier, online identifier, Internet Protocol address, email address, account name, or other similar identifiers. Collected: Yes.</li>
  <li><strong>Category B: Personal information categories listed in the California Customer Records statute (Cal. Civ. Code § 1798.80(e)).</strong> Examples: A name, signature, address, telephone number, bank account number, credit card number, or other financial information. Some personal information included in this category may overlap with other categories. Collected: Yes.</li>
  <li><strong>Category C: Protected classification characteristics under California or federal law.</strong> Collected: No.</li>
  <li><strong>Category D: Commercial information.</strong> Examples: Records and history of products or services purchased or considered. Collected: Yes.</li>
  <li><strong>Category E: Biometric information.</strong> Collected: No.</li>
  <li><strong>Category F: Internet or other similar network activity.</strong> Examples: Interaction with our Service or advertisement. Collected: Yes.</li>
  <li><strong>Category G: Geolocation data.</strong> Collected: No.</li>
  <li><strong>Category H: Sensory data.</strong> Collected: No.</li>
  <li><strong>Category I: Professional or employment-related information.</strong> Collected: No.</li>
  <li><strong>Category J: Non-public education information.</strong> Collected: No.</li>
  <li><strong>Category K: Inferences drawn from other personal information.</strong> Collected: No.</li>
</ul>
<p>Under CCPA, personal information does not include publicly available information from government records; deidentified or aggregated consumer information; or information excluded from the CCPA's scope under applicable sector-specific privacy laws.</p>

<h4>Sources of Personal Information</h4>
<p>We obtain the categories of personal information listed above from the following categories of sources:</p>
<ul>
  <li>Directly from You. For example, from the forms You complete on our Service, preferences You express or provide through our Service, or from Your purchases on our Service.</li>
  <li>Indirectly from You. For example, from observing Your activity on our Service.</li>
  <li>Automatically from You. For example, through cookies We or our Service Providers set on Your Device as You navigate through our Service.</li>
  <li>From Service Providers. For example, third-party vendors to monitor and analyze the use of our Service, third-party vendors for payment processing, or other third-party vendors that We use to provide the Service to You.</li>
</ul>

<h4>Use of Personal Information for Business Purposes or Commercial Purposes</h4>
<p>We may use or disclose personal information We collect for "business purposes" or "commercial purposes" (as defined under the CCPA), which may include the following examples:</p>
<ul>
  <li>To operate our Service and provide You with our Service.</li>
  <li>To provide You with support and to respond to Your inquiries, including to investigate and address Your concerns and monitor and improve our Service.</li>
  <li>To fulfill or meet the reason You provided the information.</li>
  <li>To respond to law enforcement requests and as required by applicable law, court order, or governmental regulations.</li>
  <li>As described to You when collecting Your personal information or as otherwise set forth in the CCPA.</li>
  <li>For internal administrative and auditing purposes.</li>
  <li>To detect security incidents and protect against malicious, deceptive, fraudulent or illegal activity, including, when necessary, to prosecute those responsible for such activities.</li>
</ul>
<p>If We decide to collect additional categories of personal information or use the personal information We collected for materially different, unrelated, or incompatible purposes We will update this Privacy Policy.</p>

<h4>Disclosure of Personal Information for Business Purposes or Commercial Purposes</h4>
<p>We may use or disclose and may have used or disclosed in the last twelve (12) months the following categories of personal information for business or commercial purposes:</p>
<ul>
  <li>Category A: Identifiers</li>
  <li>Category B: Personal information categories listed in the California Customer Records statute</li>
  <li>Category D: Commercial information</li>
  <li>Category F: Internet or other similar network activity</li>
</ul>
<p>When We disclose personal information for a business purpose or a commercial purpose, We enter a contract that describes the purpose and requires the recipient to both keep that personal information confidential and not use it for any purpose except performing the contract.</p>

<h4>Sale of Personal Information</h4>
<p>As defined in the CCPA, "sell" and "sale" mean selling, renting, releasing, disclosing, disseminating, making available, transferring, or otherwise communicating orally, in writing, or by electronic or other means, a consumer's personal information by the business to a third party for valuable consideration.</p>
<p>We may sell and may have sold in the last twelve (12) months the following categories of personal information:</p>
<ul>
  <li>Category A: Identifiers</li>
  <li>Category B: Personal information categories listed in the California Customer Records statute</li>
  <li>Category D: Commercial information</li>
  <li>Category F: Internet or other similar network activity</li>
</ul>

<h4>Share of Personal Information</h4>
<p>We may share Your personal information identified in the above categories with the following categories of third parties:</p>
<ul>
  <li>Service Providers</li>
  <li>Payment processors</li>
  <li>Our affiliates</li>
  <li>Our business partners</li>
  <li>Third party vendors to whom You or Your agents authorize Us to disclose Your personal information in connection with products or services We provide to You</li>
</ul>

<h4>Sale of Personal Information of Minors Under 16 Years of Age</h4>
<p>We do not knowingly collect personal information from minors under the age of 16 through our Service, although certain third party websites that we link to may do so. We do not sell the personal information of Consumers We actually know are less than 16 years of age, unless We receive affirmative authorization (the "right to opt-in") from either the Consumer who is between 13 and 16 years of age, or the parent or guardian of a Consumer less than 13 years of age.</p>
<p>If You have reason to believe that a child under the age of 13 (or 16) has provided Us with personal information, please contact Us with sufficient detail to enable Us to delete that information.</p>

<h4>Your Rights under the CCPA</h4>
<p>The CCPA provides California residents with specific rights regarding their personal information, including the right to notice, the right to request, the right to say no to the sale of Personal Data (opt-out), the right to delete Personal Data (subject to exceptions), and the right not to be discriminated against for exercising these rights.</p>

<h4>Exercising Your CCPA Data Protection Rights</h4>
<p>In order to exercise any of Your rights under the CCPA, and if You are a California resident, You can contact Us:</p>
<ul>
  <li>By email: <a href="mailto:privacy@tradeneu.com">privacy@tradeneu.com</a></li>
</ul>
<p>Only You, or a person registered with the California Secretary of State that You authorize to act on Your behalf, may make a verifiable request related to Your personal information.</p>
<p>Your request to Us must:</p>
<ul>
  <li>Provide sufficient information that allows Us to reasonably verify You are the person about whom We collected personal information or an authorized representative</li>
  <li>Describe Your request with sufficient detail that allows Us to properly understand, evaluate, and respond to it</li>
</ul>
<p>We will disclose and deliver the required information free of charge within 45 days of receiving Your verifiable request. The time period may be extended once by an additional 45 days when reasonably necessary and with prior notice.</p>

<h4>Do Not Sell My Personal Information</h4>
<p>You have the right to opt-out of the sale of Your personal information. Once We receive and confirm a verifiable consumer request from You, we will stop selling Your personal information. To exercise Your right to opt-out, please contact Us at <a href="mailto:privacy@tradeneu.com">privacy@tradeneu.com</a>.</p>
<p>The Service Providers we partner with (for example, our analytics or advertising partners) may use technology on the Service that sells personal information as defined by the CCPA law. You may opt out of interest-based advertising via:</p>
<ul>
  <li>The NAI's opt-out platform: <a href="http://www.networkadvertising.org/choices/" target="_blank" rel="noopener noreferrer">http://www.networkadvertising.org/choices/</a></li>
  <li>The EDAA's opt-out platform: <a href="http://www.youronlinechoices.com/" target="_blank" rel="noopener noreferrer">http://www.youronlinechoices.com/</a></li>
  <li>The DAA's opt-out platform: <a href="http://optout.aboutads.info/?c=2&amp;lang=EN" target="_blank" rel="noopener noreferrer">http://optout.aboutads.info/?c=2&amp;lang=EN</a></li>
</ul>
<p>Please note that any opt out is specific to the browser You use. You may need to opt out on every browser that You use.</p>

<h3>"Do Not Track" Policy as Required by California Online Privacy Protection Act (CalOPPA)</h3>
<p>Our Service does not respond to Do Not Track signals.</p>
<p>However, some third party websites do keep track of Your browsing activities. If You are visiting such websites, You can set Your preferences in Your web browser to inform websites that You do not want to be tracked.</p>

<h3>Children's Privacy</h3>
<p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
<p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>

<h3>Your California Privacy Rights (California's Shine the Light law)</h3>
<p>Under California Civil Code Section 1798 (California's Shine the Light law), California residents with an established business relationship with us can request information once a year about sharing their Personal Data with third parties for the third parties' direct marketing purposes.</p>
<p>If you'd like to request more information under the California Shine the Light law, and if You are a California resident, You can contact Us using the contact information provided below.</p>

<h3>California Privacy Rights for Minor Users (California Business and Professions Code Section 22581)</h3>
<p>California Business and Professions Code Section 22581 allows California residents under the age of 18 who are registered users of online sites, services or applications to request and obtain removal of content or information they have publicly posted.</p>
<p>To request removal of such data, and if You are a California resident, You can contact Us using the contact information provided below, and include the email address associated with Your account.</p>
<p>Be aware that Your request does not guarantee complete or comprehensive removal of content or information posted online and that the law may not permit or require removal in certain circumstances.</p>

<h3>Links to Other Websites</h3>
<p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
<p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

<h3>Changes to this Privacy Policy</h3>
<p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
<p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
<p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

<h3>Contact Us</h3>
<p>If you have any questions about this Privacy Policy, You can contact us:</p>
<ul>
  <li>By email: <a href="mailto:privacy@tradeneu.com">privacy@tradeneu.com</a></li>
  <li>Support: <a href="mailto:support@tradeneu.com">support@tradeneu.com</a></li>
</ul>
`
}
